spring:
  application:
    name: ai-trading-platform

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/ai_trading}

kite:
  api:
    key: ${KITE_API_KEY}
    secret: ${KITE_API_SECRET}

server:
  port: 8080
